version: 1.5.0.{build}
skip_tags: true
environment:
  Major: 1
  Minor: 5
  Patch: 0
configuration: Release
before_build:
- .\bootstrap.cmd
build:
  project: master.proj
  verbosity: normal
test: off
artifacts:
- path: '*.nupkg'
- path: '*.zip'
- path: '*.msi'
deploy:
- provider: Environment
  name: MyGet
  on:
    branch: master