//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("http://msbuildtasks.tigris.org/")]
[assembly: AssemblyProduct("MSBuild.Community.Tasks")]
[assembly: AssemblyCopyright("Copyright © 2009 MSBuild Community Tasks Project")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyVersion("1.3.0.0")]
[assembly: AssemblyFileVersion("1.3.0.460")]
[assembly: AssemblyInformationalVersion("1.3.0.460")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCompany = "http://msbuildtasks.tigris.org/";
    
    internal const string AssemblyProduct = "MSBuild.Community.Tasks";
    
    internal const string AssemblyCopyright = "Copyright © 2009 MSBuild Community Tasks Project";
    
    internal const string AssemblyVersion = "1.3.0.0";
    
    internal const string AssemblyFileVersion = "1.3.0.460";
    
    internal const string AssemblyInformationalVersion = "1.3.0.460";
    
    private ThisAssembly() {
    }
}
