//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("MSBuild Community Tasks")]
[assembly: AssemblyDescription("Collection MSBuild Tasks")]
[assembly: AssemblyCompany("http://msbuildtasks.tigris.org/")]
[assembly: AssemblyProduct("MSBuild.Community.Tasks")]
[assembly: AssemblyCopyright("Copyright © Paul Welter 2005")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("d038566a-1937-478a-b5c5-b79c4afb253d")]
[assembly: AssemblyVersion("1.0.1.92")]
[assembly: AssemblyFileVersion("1.0.1.92")]


