//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuild.Community.Tasks.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSBuild.Community.Tasks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to lookup information for {0} in Active Directory. 的本地化字符串。
        /// </summary>
        internal static string ActiveDirectoryLookupException {
            get {
                return ResourceManager.GetString("ActiveDirectoryLookupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attrib directory &apos;{0}&apos;. {1} 的本地化字符串。
        /// </summary>
        internal static string AttribDirectory {
            get {
                return ResourceManager.GetString("AttribDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attrib file &apos;{0}&apos;. {1} 的本地化字符串。
        /// </summary>
        internal static string AttribFile {
            get {
                return ResourceManager.GetString("AttribFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t connect to remove server. 的本地化字符串。
        /// </summary>
        internal static string CouldNotConnectToRemoteServer {
            get {
                return ResourceManager.GetString("CouldNotConnectToRemoteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t resolve server host name {0}. 的本地化字符串。
        /// </summary>
        internal static string CouldNotResolveServerHostName {
            get {
                return ResourceManager.GetString("CouldNotResolveServerHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating directory &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string CreatingDirectory {
            get {
                return ResourceManager.GetString("CreatingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both &quot;{0}&quot; and &quot;{1}&quot; were specified as input parameters in the project file. Please choose one or the other. 的本地化字符串。
        /// </summary>
        internal static string ExactlyOneTypeOfDestination {
            get {
                return ResourceManager.GetString("ExactlyOneTypeOfDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Not Found: {0} 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local File Not Found: {0} 的本地化字符串。
        /// </summary>
        internal static string FtpLocalNotFound {
            get {
                return ResourceManager.GetString("FtpLocalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   {0}% Complete ({1}) 的本地化字符串。
        /// </summary>
        internal static string FtpPercentComplete {
            get {
                return ResourceManager.GetString("FtpPercentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfered {0} ({1}) in {2} 的本地化字符串。
        /// </summary>
        internal static string FtpTransfered {
            get {
                return ResourceManager.GetString("FtpTransfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload File Complete, {0} 的本地化字符串。
        /// </summary>
        internal static string FtpUploadComplete {
            get {
                return ResourceManager.GetString("FtpUploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading &quot;{0}&quot;
        ///   to &quot;{1}&quot;
        /// 的本地化字符串。
        /// </summary>
        internal static string FtpUploading {
            get {
                return ResourceManager.GetString("FtpUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The URI &quot;{0}&quot; scheme is not valid. 的本地化字符串。
        /// </summary>
        internal static string FtpUriInvalid {
            get {
                return ResourceManager.GetString("FtpUriInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressed by {0}, from {1} to {2} byte(s) 的本地化字符串。
        /// </summary>
        internal static string JSCompressCompressed {
            get {
                return ResourceManager.GetString("JSCompressCompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressing JavaScript in &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string JSCompressCompressing {
            get {
                return ResourceManager.GetString("JSCompressCompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writing compressed JavaScript back to &quot;{0}&quot; using {1}. 的本地化字符串。
        /// </summary>
        internal static string JSCompressWriting {
            get {
                return ResourceManager.GetString("JSCompressWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emailing &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string MailEmailing {
            get {
                return ResourceManager.GetString("MailEmailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; is not a number. 的本地化字符串。
        /// </summary>
        internal static string MathNotNumber {
            get {
                return ResourceManager.GetString("MathNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge Complete: {0} files merged into &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MergeComplete {
            get {
                return ResourceManager.GetString("MergeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge Complete: No source files to merge. 的本地化字符串。
        /// </summary>
        internal static string MergeCompleteNoSourceFiles {
            get {
                return ResourceManager.GetString("MergeCompleteNoSourceFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merging file &apos;{0}&apos; into &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string MergingFile {
            get {
                return ResourceManager.GetString("MergingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to move file &quot;{0}&quot; to &quot;{1}&quot;. {2} 的本地化字符串。
        /// </summary>
        internal static string MoveError {
            get {
                return ResourceManager.GetString("MoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving file from &quot;{0}&quot; to &quot;{1}&quot;. 的本地化字符串。
        /// </summary>
        internal static string MoveFileComment {
            get {
                return ResourceManager.GetString("MoveFileComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find the NUnit Project File open command. Please make sure NUnit is installed. 的本地化字符串。
        /// </summary>
        internal static string NUnitNotFound {
            get {
                return ResourceManager.GetString("NUnitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking Oracle Home: {0} 的本地化字符串。
        /// </summary>
        internal static string OracleHomeCheck {
            get {
                return ResourceManager.GetString("OracleHomeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter &quot;{1}&quot; does not apply to the current use of task &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ParameterNotUsed {
            get {
                return ResourceManager.GetString("ParameterNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &quot;{0}&quot; task was not given a value for the required parameter &quot;{1}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ParameterRequired {
            get {
                return ResourceManager.GetString("ParameterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read Windows Registry 的本地化字符串。
        /// </summary>
        internal static string RegistryRead {
            get {
                return ResourceManager.GetString("RegistryRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write Windows Registry 的本地化字符串。
        /// </summary>
        internal static string RegistryWrite {
            get {
                return ResourceManager.GetString("RegistryWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot continue service {0} on computer &apos;{1}&apos; as it does not support the pause and continue. 的本地化字符串。
        /// </summary>
        internal static string ServiceCannotContinue {
            get {
                return ResourceManager.GetString("ServiceCannotContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot pause service {0} on computer &apos;{1}&apos; as it does not support the pause and continue. 的本地化字符串。
        /// </summary>
        internal static string ServiceCannotPause {
            get {
                return ResourceManager.GetString("ServiceCannotPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot stop service {0} on computer &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ServiceCannotStop {
            get {
                return ResourceManager.GetString("ServiceCannotStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} service was continued successfully. 的本地化字符串。
        /// </summary>
        internal static string ServiceContinued {
            get {
                return ResourceManager.GetString("ServiceContinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} service is continuing ... 的本地化字符串。
        /// </summary>
        internal static string ServiceContinuing {
            get {
                return ResourceManager.GetString("ServiceContinuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t find the &apos;{0}&apos; service on &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot continue service {0} on computer &apos;{1}&apos; as its not currently paused. 的本地化字符串。
        /// </summary>
        internal static string ServiceNotPaused {
            get {
                return ResourceManager.GetString("ServiceNotPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot pause service {0} on computer &apos;{1}&apos; as its not currently started. 的本地化字符串。
        /// </summary>
        internal static string ServiceNotStarted {
            get {
                return ResourceManager.GetString("ServiceNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} service was paused successfully. 的本地化字符串。
        /// </summary>
        internal static string ServicePaused {
            get {
                return ResourceManager.GetString("ServicePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} service is pausing ... 的本地化字符串。
        /// </summary>
        internal static string ServicePausing {
            get {
                return ResourceManager.GetString("ServicePausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} service was started successfully. 的本地化字符串。
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} service is starting ... 的本地化字符串。
        /// </summary>
        internal static string ServiceStarting {
            get {
                return ResourceManager.GetString("ServiceStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; service on &apos;{1}&apos; is &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ServiceStatus {
            get {
                return ResourceManager.GetString("ServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} service was stopped successfully. 的本地化字符串。
        /// </summary>
        internal static string ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} service is stopping ... 的本地化字符串。
        /// </summary>
        internal static string ServiceStopping {
            get {
                return ResourceManager.GetString("ServiceStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solution file &quot;{0}&quot; not found. 的本地化字符串。
        /// </summary>
        internal static string SolutionNotFound {
            get {
                return ResourceManager.GetString("SolutionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalPath is not a working subversion copy. 的本地化字符串。
        /// </summary>
        internal static string SvnLocalPathNotWorkCopy {
            get {
                return ResourceManager.GetString("SvnLocalPathNotWorkCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not {0} the file &quot;{1}&quot; to the destination file &quot;{2}&quot;, because the destination is a folder instead of a file. To {0} the source file into a folder, consider using the DestinationFolder parameter instead of DestinationFiles. 的本地化字符串。
        /// </summary>
        internal static string TaskDestinationIsDirectory {
            get {
                return ResourceManager.GetString("TaskDestinationIsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No destination specified for {0}. Please supply either &quot;{1}&quot; or &quot;{2}&quot;. 的本地化字符串。
        /// </summary>
        internal static string TaskNeedsDestination {
            get {
                return ResourceManager.GetString("TaskNeedsDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The source file &quot;{0}&quot; is actually a directory.  The &quot;{1}&quot; task does not support moving directories. 的本地化字符串。
        /// </summary>
        internal static string TaskSourceIsDirectory {
            get {
                return ResourceManager.GetString("TaskSourceIsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get current date! 的本地化字符串。
        /// </summary>
        internal static string TimeFormatException {
            get {
                return ResourceManager.GetString("TimeFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting current date. 的本地化字符串。
        /// </summary>
        internal static string TimeGettingCurrentDate {
            get {
                return ResourceManager.GetString("TimeGettingCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding TNSNAMES entry &quot;{0}&quot; to &quot;{1}&quot; 的本地化字符串。
        /// </summary>
        internal static string TnsnameAdded {
            get {
                return ResourceManager.GetString("TnsnameAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Looking for {0} 的本地化字符串。
        /// </summary>
        internal static string TnsNamesFileCheck {
            get {
                return ResourceManager.GetString("TnsNamesFileCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to locate a TNSNAMES.ORA file. Please specify a value for TnsNamesFile. 的本地化字符串。
        /// </summary>
        internal static string TnsNamesFileNotFound {
            get {
                return ResourceManager.GetString("TnsNamesFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TNSNAME entry &quot;{0}&quot; already exists in &quot;{1}&quot; and AllowUpdates=false. 的本地化字符串。
        /// </summary>
        internal static string TnsnameUpdateAborted {
            get {
                return ResourceManager.GetString("TnsnameUpdateAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating TNSNAMES entry &quot;{0}&quot; in &quot;{1}&quot; 的本地化字符串。
        /// </summary>
        internal static string TnsnameUpdated {
            get {
                return ResourceManager.GetString("TnsnameUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{2}&quot; refers to {0} item(s), and &quot;{3}&quot; refers to {1} item(s). They must have the same number of items. 的本地化字符串。
        /// </summary>
        internal static string TwoVectorsMustHaveSameLength {
            get {
                return ResourceManager.GetString("TwoVectorsMustHaveSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   extracted &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string UnzipExtracted {
            get {
                return ResourceManager.GetString("UnzipExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unzip File &quot;{0}&quot;
        ///    to Directory &quot;{1}&quot;
        /// 的本地化字符串。
        /// </summary>
        internal static string UnzipFileToDirectory {
            get {
                return ResourceManager.GetString("UnzipFileToDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unzipped file &quot;{0}&quot; successfully. 的本地化字符串。
        /// </summary>
        internal static string UnzipSuccessfully {
            get {
                return ResourceManager.GetString("UnzipSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commitment of change set failed! 的本地化字符串。
        /// </summary>
        internal static string VaultAddFileCommitFailed {
            get {
                return ResourceManager.GetString("VaultAddFileCommitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files added to Vault repository successfully. 的本地化字符串。
        /// </summary>
        internal static string VaultAddFileCommitSucceeded {
            get {
                return ResourceManager.GetString("VaultAddFileCommitSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files specified for addition to repository cannot be found. 的本地化字符串。
        /// </summary>
        internal static string VaultAddFilesException {
            get {
                return ResourceManager.GetString("VaultAddFilesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file {0} could not be checked in: {1}. 的本地化字符串。
        /// </summary>
        internal static string VaultCheckinFileException {
            get {
                return ResourceManager.GetString("VaultCheckinFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File or folder {0} not found for checkin. 的本地化字符串。
        /// </summary>
        internal static string VaultCheckinFileNotFoundException {
            get {
                return ResourceManager.GetString("VaultCheckinFileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The folder {0} could not be checked in: {1}. 的本地化字符串。
        /// </summary>
        internal static string VaultCheckinFolderException {
            get {
                return ResourceManager.GetString("VaultCheckinFolderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} successfully checked out. 的本地化字符串。
        /// </summary>
        internal static string VaultCheckinSuccessful {
            get {
                return ResourceManager.GetString("VaultCheckinSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} successfully checked out. 的本地化字符串。
        /// </summary>
        internal static string VaultCheckoutSuccessful {
            get {
                return ResourceManager.GetString("VaultCheckoutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified diskfile {0} does not exist. 的本地化字符串。
        /// </summary>
        internal static string VaultDiskFileDoesNotExist {
            get {
                return ResourceManager.GetString("VaultDiskFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File [{0}] added to change set. 的本地化字符串。
        /// </summary>
        internal static string VaultFileAddedToChangeSet {
            get {
                return ResourceManager.GetString("VaultFileAddedToChangeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder [{0}] added to change set. 的本地化字符串。
        /// </summary>
        internal static string VaultFolderAddedToChangeSet {
            get {
                return ResourceManager.GetString("VaultFolderAddedToChangeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect parameters passed to VaultSession. 的本地化字符串。
        /// </summary>
        internal static string VaultIncorrectParameters {
            get {
                return ResourceManager.GetString("VaultIncorrectParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login to Vault repository failed. 的本地化字符串。
        /// </summary>
        internal static string VaultLoginFailed {
            get {
                return ResourceManager.GetString("VaultLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error validating path &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string VaultPathValidationException {
            get {
                return ResourceManager.GetString("VaultPathValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection of the repository failed: {0}. 的本地化字符串。
        /// </summary>
        internal static string VaultRepositorySelectionFailure {
            get {
                return ResourceManager.GetString("VaultRepositorySelectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File or folder {0} not found for checkout. 的本地化字符串。
        /// </summary>
        internal static string VaultResourceNotFound {
            get {
                return ResourceManager.GetString("VaultResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set working folder for {0} to {1} from {2}. 的本地化字符串。
        /// </summary>
        internal static string VaultSetNewWorkingFolder {
            get {
                return ResourceManager.GetString("VaultSetNewWorkingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClientInstance.TreeCache has not been initialized, Common cause is that SelectRepository has not been called sucessfully. 的本地化字符串。
        /// </summary>
        internal static string VaultTreeCacheFailure {
            get {
                return ResourceManager.GetString("VaultTreeCacheFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully undid check out for {0}. 的本地化字符串。
        /// </summary>
        internal static string VaultUndoCheckoutSuccessful {
            get {
                return ResourceManager.GetString("VaultUndoCheckoutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url specifying vault location is required. 的本地化字符串。
        /// </summary>
        internal static string VaultUrlRequired {
            get {
                return ResourceManager.GetString("VaultUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username must be set to access repository. 的本地化字符串。
        /// </summary>
        internal static string VaultUsernameRequired {
            get {
                return ResourceManager.GetString("VaultUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clearing working folder for {0}. 的本地化字符串。
        /// </summary>
        internal static string VaultWorkingFolderCleared {
            get {
                return ResourceManager.GetString("VaultWorkingFolderCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restoring working folder for {0} to {1}. 的本地化字符串。
        /// </summary>
        internal static string VaultWorkingFolderRestored {
            get {
                return ResourceManager.GetString("VaultWorkingFolderRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version file &quot;{0}&quot; not found - creating new file. 的本地化字符串。
        /// </summary>
        internal static string VersionFileNotFound {
            get {
                return ResourceManager.GetString("VersionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated to version {0} 的本地化字符串。
        /// </summary>
        internal static string VersionModifiedValue {
            get {
                return ResourceManager.GetString("VersionModifiedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialized to version {0} 的本地化字符串。
        /// </summary>
        internal static string VersionOriginalValue {
            get {
                return ResourceManager.GetString("VersionOriginalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading version from file &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string VersionRead {
            get {
                return ResourceManager.GetString("VersionRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to read version number from &quot;{0}&quot;. {1} 的本地化字符串。
        /// </summary>
        internal static string VersionReadException {
            get {
                return ResourceManager.GetString("VersionReadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to write version number to &quot;{0}&quot;. {1}&quot; 的本地化字符串。
        /// </summary>
        internal static string VersionWriteException {
            get {
                return ResourceManager.GetString("VersionWriteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrote version to file &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string VersionWrote {
            get {
                return ResourceManager.GetString("VersionWrote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web directory {0} does not exist on {1}. 的本地化字符串。
        /// </summary>
        internal static string WebDirectoryInvalidDirectory {
            get {
                return ResourceManager.GetString("WebDirectoryInvalidDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting scriptmap for {0} on web directory {1} on {2}. 的本地化字符串。
        /// </summary>
        internal static string WebDirectoryScriptMapUpdate {
            get {
                return ResourceManager.GetString("WebDirectoryScriptMapUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web directory {0} on {1} does not have a setting called {2}. 的本地化字符串。
        /// </summary>
        internal static string WebDirectorySettingInvalidSetting {
            get {
                return ResourceManager.GetString("WebDirectorySettingInvalidSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading {0} property of web directory {1} on {2}. 的本地化字符串。
        /// </summary>
        internal static string WebDirectorySettingStatusRead {
            get {
                return ResourceManager.GetString("WebDirectorySettingStatusRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting {0} property of web directory {1} on {2}. 的本地化字符串。
        /// </summary>
        internal static string WebDirectorySettingStatusSet {
            get {
                return ResourceManager.GetString("WebDirectorySettingStatusSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading Xml Document &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string XmlReadDocument {
            get {
                return ResourceManager.GetString("XmlReadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   {0} node(s) selected for read. 的本地化字符串。
        /// </summary>
        internal static string XmlReadNodes {
            get {
                return ResourceManager.GetString("XmlReadNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XmlRead Result: &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string XmlReadResult {
            get {
                return ResourceManager.GetString("XmlReadResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating Xml Document &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string XmlUpdateDocument {
            get {
                return ResourceManager.GetString("XmlUpdateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   {0} node(s) selected for update. 的本地化字符串。
        /// </summary>
        internal static string XmlUpdateNodes {
            get {
                return ResourceManager.GetString("XmlUpdateNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XmlUpdate Wrote: &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string XmlUpdateResult {
            get {
                return ResourceManager.GetString("XmlUpdateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding Parameter &quot;{0}&quot;: &quot;{1}&quot;. 的本地化字符串。
        /// </summary>
        internal static string XsltAddingParameter {
            get {
                return ResourceManager.GetString("XsltAddingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding root attribute {0}=&quot;{1}&quot;. 的本地化字符串。
        /// </summary>
        internal static string XsltAddingRootAttribute {
            get {
                return ResourceManager.GetString("XsltAddingRootAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating root tag &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string XsltCreatingRootTag {
            get {
                return ResourceManager.GetString("XsltCreatingRootTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No input files. 的本地化字符串。
        /// </summary>
        internal static string XsltNoInputFiles {
            get {
                return ResourceManager.GetString("XsltNoInputFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No root tag inserted. 的本地化字符串。
        /// </summary>
        internal static string XsltNoRootTag {
            get {
                return ResourceManager.GetString("XsltNoRootTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   added &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ZipAdded {
            get {
                return ResourceManager.GetString("ZipAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating zip file &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ZipCreating {
            get {
                return ResourceManager.GetString("ZipCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zip File Not Found: {0}. 的本地化字符串。
        /// </summary>
        internal static string ZipFileNotFound {
            get {
                return ResourceManager.GetString("ZipFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created zip file &quot;{0}&quot; successfully. 的本地化字符串。
        /// </summary>
        internal static string ZipSuccessfully {
            get {
                return ResourceManager.GetString("ZipSuccessfully", resourceCulture);
            }
        }
    }
}
