//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("https://github.com/loresoft/msbuildtasks/")]
[assembly: AssemblyProduct("MSBuild.Community.Tasks")]
[assembly: AssemblyCopyright("Copyright © 2012 MSBuild Community Tasks Project")]
[assembly: AssemblyConfiguration("Commit 8663c5c")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyVersion("1.4.0.0")]
[assembly: AssemblyFileVersion("1.4.0.0")]
[assembly: AssemblyInformationalVersion("1.4.0.0")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCompany = "https://github.com/loresoft/msbuildtasks/";
    
    internal const string AssemblyProduct = "MSBuild.Community.Tasks";
    
    internal const string AssemblyCopyright = "Copyright © 2012 MSBuild Community Tasks Project";
    
    internal const string AssemblyConfiguration = "Commit 8663c5c";
    
    internal const string AssemblyVersion = "1.4.0.0";
    
    internal const string AssemblyFileVersion = "1.4.0.0";
    
    internal const string AssemblyInformationalVersion = "1.4.0.0";
    
    private ThisAssembly() {
    }
}
