//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("MSBuild.Community.Tasks")]
[assembly: System.Reflection.AssemblyCompany("https://github.com/loresoft/msbuildtasks/")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2014 MSBuild Community Tasks Project")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("1.4.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.4.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.4.0.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyProduct = "MSBuild.Community.Tasks";
    
    internal const string AssemblyCompany = "https://github.com/loresoft/msbuildtasks/";
    
    internal const string AssemblyCopyright = "Copyright © 2014 MSBuild Community Tasks Project";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyVersion = "1.4.0.0";
    
    internal const string AssemblyFileVersion = "1.4.0.0";
    
    internal const string AssemblyInformationalVersion = "1.4.0.0";
    
    private ThisAssembly() {
    }
}
